```bash
#!/bin/bash

###############################################################################
# Simple server helper menu
###############################################################################

msgbox() {
    echo
    echo "=============================="
    echo "$1"
    echo "=============================="
    echo
}

###############################################################################
# Functions
###############################################################################

# --- System update ---

update_all() {
    apt-get update && apt-get upgrade -y
}

update_all_with_sudo_reboot() {
    # keep sudo at the beginning as requested
    sudo apt install sudo && sudo apt-get update && sudo apt-get upgrade -y && sudo reboot
}

# --- DNS management ---

show_dns() {
    cat /etc/resolv.conf
}

edit_dns() {
    nano /etc/resolv.conf
}

# Append Netcup DNS (46.38.225.230 + 1.1.1.1)
add_dns_netcup_append() {
    echo -e "nameserver 46.38.225.230\nnameserver 1.1.1.1" | tee -a /etc/resolv.conf > /dev/null
}

# Overwrite with Netcup DNS (46.38.225.230 + 1.1.1.1)
set_dns_netcup_overwrite() {
    cat <<EOF > /etc/resolv.conf
nameserver 46.38.225.230
nameserver 1.1.1.1
EOF
}

# Overwrite with Cloudflare + Google DNS (1.1.1.1 + 8.8.8.8)
set_dns_cloudflare_google() {
    cat <<EOF > /etc/resolv.conf
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF
}

# --- Networking / IP ---

whats_my_ip() {
    dig +short myip.opendns.com @resolver1.opendns.com
}

show_ifconfig() {
    ifconfig
}

# --- Speedtest & benchmarks ---

install_speedtest_full() {
    apt-get install curl -y
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash
    apt-get install speedtest -y
}

change_speedtest_apt_list() {
    cat <<EOF > /etc/apt/sources.list.d/ookla_speedtest-cli.list
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/ookla/speedtest-cli

deb [signed-by=/etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/ubuntu/ jammy main
deb-src [signed-by=/etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/ubuntu/ jammy main
EOF
}

install_speedtest_after_list() {
    apt-get update && apt-get install speedtest -y
}

run_speedtest() {
    speedtest
}

run_yabs() {
    curl -sL https://yabs.sh | bash
}

# --- SSH / remote access ---

change_ssh_proxmox() {
    curl -fsSL "https://cloud.io.anatolium.eu/s/jR9crxfoLHz5474/download" | bash
}

install_openssh() {
    apt update
    apt install openssh-server -y
    systemctl enable --now ssh
}

tailscale_install() {
    curl -fsSL https://tailscale.com/install.sh | sh
}

tailscale_up_qr() {
    tailscale up -qr
}

# --- Tools & environment ---

install_essentials() {
    apt update
    apt-get install sudo -y
    apt-get install nano -y
    apt-get install curl -y
    apt-get install net-tools -y
}

install_tools() {
    apt update
    apt-get install sudo curl net-tools -y
    apt install unzip -y
    apt install python3-pip -y
    apt-get install gcc python3-dev -y
    pip install --no-binary :all: psutil
    pip3 install gdown
    apt install dos2unix -y
    apt install glances -y
    apt install tmux -y
    apt install zsh -y
    apt install mc -y
}

install_ibramenu() {
    wget -qO ./i https://raw.githubusercontent.com/ibracorp/ibramenu/main/ibrainit.sh
    chmod +x i
    ./i
}

install_qemu_guest_agent() {
    apt update
    apt install qemu-guest-agent -y
    systemctl enable --now qemu-guest-agent
}

# --- System information ---

os_release_check() {
    cat /etc/os-release
}

general_information() {
    apt install neofetch -y
    msgbox "Neofetch"
    neofetch
}

memory_information() {
    msgbox "Memory Information"
    free -h
    read -p "Press Enter to continue..."
    dmidecode -t memory
}

# --- System control ---

system_reboot() {
    msgbox "System Reboot"
    read -p "Are you sure (y/N)? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        reboot
    fi
}

system_powerdown() {
    msgbox "System Power Down"
    read -p "Are you sure (y/N)? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        /sbin/shutdown -h now
    fi
}

###############################################################################
# Menu
###############################################################################

show_menu() {
    echo "================= SYSTEM UPDATE ================="
    echo " 1) Update all (apt-get update && upgrade)"
    echo " 2) Update all with sudo and reboot"
    echo
    echo "================= DNS MANAGEMENT ================="
    echo " 3) Show DNS (/etc/resolv.conf)"
    echo " 4) Edit DNS (/etc/resolv.conf in nano)"
    echo " 5) Append Netcup DNS 46.38.225.230 + 1.1.1.1"
    echo " 6) Overwrite Netcup DNS 46.38.225.230 + 1.1.1.1"
    echo " 7) Overwrite DNS with 1.1.1.1 + 8.8.8.8"
    echo
    echo "================ NETWORK / IP ===================="
    echo " 8) Show public IP (dig / OpenDNS)"
    echo " 9) Show ifconfig"
    echo
    echo "============= SPEEDTEST & BENCHMARKS ============="
    echo "10) Install Speedtest (repo + package)"
    echo "11) Update Speedtest repo list (jammy)"
    echo "12) Install Speedtest after repo update"
    echo "13) Run Speedtest"
    echo "14) Run YABS (Yet-Another-Bench-Script)"
    echo
    echo "============= SSH / REMOTE ACCESS ================"
    echo "15) Update SSH config for Proxmox (remote script)"
    echo "16) Install OpenSSH server"
    echo "17) Install Tailscale"
    echo "18) Tailscale up (QR mode)"
    echo
    echo "========== TOOLS & ENVIRONMENT SETUP ============="
    echo "19) Install essentials (sudo, nano, curl, net-tools)"
    echo "20) Install extra tools (unzip, python, gdown, glances, tmux, zsh, mc)"
    echo "21) Install ibramenu"
    echo "22) Install QEMU guest agent"
    echo
    echo "============ SYSTEM INFORMATION =================="
    echo "23) Show /etc/os-release"
    echo "24) General system info (neofetch)"
    echo "25) Memory information"
    echo
    echo "============== SYSTEM CONTROL ===================="
    echo "26) Reboot"
    echo "27) Power down"
    echo
    echo " 0) Exit"
    echo "================================================="
}

###############################################################################
# Main
###############################################################################

# Root check
if [[ $EUID -ne 0 ]]; then
   echo "Please run as root (e.g. sudo bash $0)."
   exit 1
fi

while true; do
    show_menu
    read -p "Select an option: " choice
    case "$choice" in
        1)  update_all ;;
        2)  update_all_with_sudo_reboot ;;
        3)  show_dns ;;
        4)  edit_dns ;;
        5)  add_dns_netcup_append ;;
        6)  set_dns_netcup_overwrite ;;
        7)  set_dns_cloudflare_google ;;
        8)  whats_my_ip ;;
        9)  show_ifconfig ;;
        10) install_speedtest_full ;;
        11) change_speedtest_apt_list ;;
        12) install_speedtest_after_list ;;
        13) run_speedtest ;;
        14) run_yabs ;;
        15) change_ssh_proxmox ;;
        16) install_openssh ;;
        17) tailscale_install ;;
        18) tailscale_up_qr ;;
        19) install_essentials ;;
        20) install_tools ;;
        21) install_ibramenu ;;
        22) install_qemu_guest_agent ;;
        23) os_release_check ;;
        24) general_information ;;
        25) memory_information ;;
        26) system_reboot ;;
        27) system_powerdown ;;
        0)  echo "Exiting."; exit 0 ;;
        *)  echo "Invalid choice." ;;
    esac
    echo
    read -p "Press Enter to continue..."
done
```
